<a href="https://colab.research.google.com/github/KalonzoBrian/LEARNING-PYTHON/blob/main/Loan_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Data Loading and Initial Exploration

I will load the training and test datasets into pandas DataFrames. For the zipped files, I will first extract them.

In [5]:
import pandas as pd
import zipfile
import os

# Load trainperf.csv
train_perf_df = pd.read_csv('/content/trainperf.csv')
print('trainperf.csv loaded. First 5 rows:')
display(train_perf_df.head())

# Load testperf.csv
test_perf_df = pd.read_csv('/content/testperf.csv')
print('\ntestperf.csv loaded. First 5 rows:')
display(test_perf_df.head())

trainperf.csv loaded. First 5 rows:

,customerid,systemloanid,loannumber,approveddate,creationdate,loanamount,totaldue,termdays,referredby,good_bad_flag
0,8a2a81a74ce8c05d014cfb32a0da1049,301994762,12,2017-07-25 08:22:56.000000,2017-07-25 07:22:47.000000,30000.0,34500.0,30,NaN,Good
1,8a85886e54beabf90154c0a29ae757c0,301965204,2,2017-07-05 17:04:41.000000,2017-07-05 16:04:18.000000,15000.0,17250.0,30,NaN,Good
2,8a8588f35438fe12015444567666018e,301966580,7,2017-07-06 14:52:57.000000,2017-07-06 13:52:51.000000,20000.0,22250.0,15,NaN,Good
3,8a85890754145ace015429211b513e16,301999343,3,2017-07-27 19:00:41.000000,2017-07-27 18:00:35.000000,10000.0,11500.0,15,NaN,Good
4,8a858970548359cc0154883481981866,301962360,9,2017-07-03 23:42:45.000000,2017-07-03 22:42:39.000000,40000.0,44000.0,30,NaN,Good

testperf.csv loaded. First 5 rows:

,customerid,systemloanid,loannumber,approveddate,creationdate,loanamount,totaldue,termdays,referredby
0,8a858899538ddb8e015390510b321f08,301998974,4,40:48.0,39:35.0,10000,12250.0,30,NaN
1,8a858959537a097401537a4e316e25f7,301963615,10,43:40.0,42:34.0,40000,44000.0,30,NaN
2,8a8589c253ace09b0153af6ba58f1f31,301982236,6,15:11.0,15:04.0,20000,24500.0,30,NaN
3,8a858e095aae82b7015aae86ca1e030b,301971730,8,00:54.0,00:49.0,30000,34500.0,30,NaN
4,8a858e225a28c713015a30db5c48383d,301959177,4,04:33.0,04:27.0,20000,24500.0,30,NaN

In [6]:
# Load traindemographics.csv
train_demographics_df = pd.read_csv('/content/traindemographics.csv')
print('traindemographics.csv loaded. First 5 rows:')
display(train_demographics_df.head())

# Load testdemographics.csv
test_demographics_df = pd.read_csv('/content/testdemographics.csv')
print('\ntestdemographics.csv loaded. First 5 rows:')
display(test_demographics_df.head())

traindemographics.csv loaded. First 5 rows:

,customerid,birthdate,bank_account_type,longitude_gps,latitude_gps,bank_name_clients,bank_branch_clients,employment_status_clients,level_of_education_clients
0,8a858e135cb22031015cbafc76964ebd,1973-10-10 00:00:00.000000,Savings,3.319219,6.528604,GT Bank,NaN,NaN,NaN
1,8a858e275c7ea5ec015c82482d7c3996,1986-01-21 00:00:00.000000,Savings,3.325598,7.119403,Sterling Bank,NaN,Permanent,NaN
2,8a858e5b5bd99460015bdc95cd485634,1987-04-01 00:00:00.000000,Savings,5.746100,5.563174,Fidelity Bank,NaN,NaN,NaN
3,8a858efd5ca70688015cabd1f1e94b55,1991-07-19 00:00:00.000000,Savings,3.362850,6.642485,GT Bank,NaN,Permanent,NaN
4,8a858e785acd3412015acd48f4920d04,1982-11-22 00:00:00.000000,Savings,8.455332,11.971410,GT Bank,NaN,Permanent,NaN

testdemographics.csv loaded. First 5 rows:

,customerid,birthdate,bank_account_type,longitude_gps,latitude_gps,bank_name_clients,bank_branch_clients,employment_status_clients,level_of_education_clients
0,8a858f305c8dd672015c93b1db645db4,1976-08-28 00:00:00.000000,Savings,5.296628,7.593965,Heritage Bank,NaN,Permanent,NaN
1,8a858f085a477386015a47fb049e49ca,1978-06-23 00:00:00.000000,Savings,3.294513,6.596602,UBA,NaN,Permanent,NaN
2,8a858e6f5cd5e874015cd6f5634c39ad,1984-04-04 00:00:00.000000,Savings,8.501912,7.729364,First Bank,NaN,Permanent,NaN
3,8a858e9d5bfd7037015bfdab79f61305,1983-05-28 00:00:00.000000,Savings,3.318904,6.681595,UBA,NaN,Permanent,NaN
4,8a858fde56eb02280156eb6dafc128ac,1982-03-29 00:00:00.000000,Savings,6.354624,4.949031,First Bank,NaN,Self-Employed,NaN

In [7]:
# Extract and load trainprevloans.zip
with zipfile.ZipFile('/content/trainprevloans.zip', 'r') as zip_ref:
    zip_ref.extractall('/content/')
train_prev_loans_df = pd.read_csv('/content/trainprevloans.csv')
print('\ntrainprevloans.csv loaded. First 5 rows:')
display(train_prev_loans_df.head())

# Extract and load testprevloans.zip
with zipfile.ZipFile('/content/testprevloans.zip', 'r') as zip_ref:
    zip_ref.extractall('/content/')
test_prev_loans_df = pd.read_csv('/content/testprevloans.csv')
print('\ntestprevloans.csv loaded. First 5 rows:')
display(test_prev_loans_df.head())

trainprevloans.csv loaded. First 5 rows:

,customerid,systemloanid,loannumber,approveddate,creationdate,loanamount,totaldue,termdays,closeddate,referredby,firstduedate,firstrepaiddate
0,8a2a81a74ce8c05d014cfb32a0da1049,301682320,2,2016-08-15 18:22:40.000000,2016-08-15 17:22:32.000000,10000.0,13000.0,30,2016-09-01 16:06:48.000000,NaN,2016-09-14 00:00:00.000000,2016-09-01 15:51:43.000000
1,8a2a81a74ce8c05d014cfb32a0da1049,301883808,9,2017-04-28 18:39:07.000000,2017-04-28 17:38:53.000000,10000.0,13000.0,30,2017-05-28 14:44:49.000000,NaN,2017-05-30 00:00:00.000000,2017-05-26 00:00:00.000000
2,8a2a81a74ce8c05d014cfb32a0da1049,301831714,8,2017-03-05 10:56:25.000000,2017-03-05 09:56:19.000000,20000.0,23800.0,30,2017-04-26 22:18:56.000000,NaN,2017-04-04 00:00:00.000000,2017-04-26 22:03:47.000000
3,8a8588f35438fe12015444567666018e,301861541,5,2017-04-09 18:25:55.000000,2017-04-09 17:25:42.000000,10000.0,11500.0,15,2017-04-24 01:35:52.000000,NaN,2017-04-24 00:00:00.000000,2017-04-24 00:48:43.000000
4,8a85890754145ace015429211b513e16,301941754,2,2017-06-17 09:29:57.000000,2017-06-17 08:29:50.000000,10000.0,11500.0,15,2017-07-14 21:18:43.000000,NaN,2017-07-03 00:00:00.000000,2017-07-14 21:08:35.000000

testprevloans.csv loaded. First 5 rows:

,customerid,systemloanid,loannumber,approveddate,creationdate,loanamount,totaldue,termdays,closeddate,referredby,firstduedate,firstrepaiddate
0,8a858899538ddb8e015390510b321f08,301621635,3,2016-05-17 10:37:00.000000,2016-05-17 09:36:55.000000,10000.0,13000.0,30,2016-06-17 00:04:15.000000,NaN,2016-06-16 00:00:00.000000,2016-06-16 15:44:08.000000
1,8a858959537a097401537a4e316e25f7,301810201,5,2017-02-04 21:28:59.000000,2017-02-04 20:28:52.000000,30000.0,36800.0,60,2017-03-02 16:22:58.000000,NaN,2017-03-06 00:00:00.000000,2017-03-02 16:07:47.000000
2,8a858959537a097401537a4e316e25f7,301831255,6,2017-03-04 10:28:22.000000,2017-03-04 09:28:16.000000,30000.0,34400.0,30,2017-04-02 00:44:24.000000,NaN,2017-04-03 00:00:00.000000,2017-04-01 21:29:46.000000
3,8a8589c253ace09b0153af6ba58f1f31,301627292,3,2016-06-02 14:27:14.000000,2016-06-02 13:27:08.000000,10000.0,13000.0,30,2016-07-04 11:34:04.000000,NaN,2016-07-04 00:00:00.000000,2016-07-04 11:19:01.000000
4,8a8589c253ace09b0153af6ba58f1f31,301621095,2,2016-05-16 09:13:12.000000,2016-05-16 08:13:04.000000,10000.0,11500.0,15,2016-06-02 00:02:58.000000,NaN,2016-05-31 00:00:00.000000,2016-06-01 15:22:34.000000

In [8]:
# Load SampleSubmission (1).csv
sample_submission_df = pd.read_csv('/content/SampleSubmission (1).csv')
print('\nSampleSubmission (1).csv loaded. First 5 rows:')
display(sample_submission_df.head())

SampleSubmission (1).csv loaded. First 5 rows:

                         customerid  Good_Bad_flag
0  8a28afc7474813a40147639ec637156b              1
1  8a3735d5518aba7301518ac34413010d              1
2  8a76e7d443e6e97c0143ed099d102b1d              1
3  8a818823525dceef01525deda2480384              1
4  8a818926522ea5ef01523aff15c37482              1

## Data Cleaning and Preprocessing - Performance Data

I will start by examining the `train_perf_df` and `test_perf_df` for data types and missing values, and convert relevant columns to datetime objects.

In [9]:
print('--- train_perf_df info ---')
train_perf_df.info()
print('\n--- test_perf_df info ---')
test_perf_df.info()

--- train_perf_df info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4368 entries, 0 to 4367
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customerid     4368 non-null   object
 1   systemloanid   4368 non-null   int64
 2   loannumber     4368 non-null   int64
 3   approveddate   4368 non-null   object
 4   creationdate   4368 non-null   object
 5   loanamount     4368 non-null   float64
 6   totaldue       4368 non-null   float64
 7   termdays       4368 non-null   int64
 8   referredby     587 non-null    object
 9   good_bad_flag  4368 non-null   object
dtypes: float64(2), int64(3), object(5)
memory usage: 341.4+ KB

--- test_perf_df info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1450 entries, 0 to 1449
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   customerid    1450 non-null   object
 1   systemloanid  1450 non-null   int64
 2   loannumber    1450 non-null   int64
 3   approveddate  1450 non-null   object
 4   creationdate  1450 non-null   object
 5   loanamount    1450 non-null   int64
 6   totaldue      1450 non-null   float64
 7   termdays      1450 non-null   int64
 8   referredby    184 non-null    object
dtypes: float64(1), int64(4), object(4)
memory usage: 102.1+ KB

In [10]:
# Convert date columns to datetime objects for train_perf_df
for col in ['approveddate', 'creationdate']:
    train_perf_df[col] = pd.to_datetime(train_perf_df[col], errors='coerce')

# Convert date columns to datetime objects for test_perf_df
for col in ['approveddate', 'creationdate']:
    test_perf_df[col] = pd.to_datetime(test_perf_df[col], errors='coerce')

print('\nDate columns converted for train_perf_df:')
display(train_perf_df.head())
print('\nDate columns converted for test_perf_df:')
display(test_perf_df.head())

Date columns converted for train_perf_df:

/tmp/ipykernel_4142/4270472321.py:7: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  test_perf_df[col] = pd.to_datetime(test_perf_df[col], errors='coerce')
/tmp/ipykernel_4142/4270472321.py:7: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  test_perf_df[col] = pd.to_datetime(test_perf_df[col], errors='coerce')

,customerid,systemloanid,loannumber,approveddate,creationdate,loanamount,totaldue,termdays,referredby,good_bad_flag
0,8a2a81a74ce8c05d014cfb32a0da1049,301994762,12,2017-07-25 08:22:56,2017-07-25 07:22:47,30000.0,34500.0,30,NaN,Good
1,8a85886e54beabf90154c0a29ae757c0,301965204,2,2017-07-05 17:04:41,2017-07-05 16:04:18,15000.0,17250.0,30,NaN,Good
2,8a8588f35438fe12015444567666018e,301966580,7,2017-07-06 14:52:57,2017-07-06 13:52:51,20000.0,22250.0,15,NaN,Good
3,8a85890754145ace015429211b513e16,301999343,3,2017-07-27 19:00:41,2017-07-27 18:00:35,10000.0,11500.0,15,NaN,Good
4,8a858970548359cc0154883481981866,301962360,9,2017-07-03 23:42:45,2017-07-03 22:42:39,40000.0,44000.0,30,NaN,Good

Date columns converted for test_perf_df:

,customerid,systemloanid,loannumber,approveddate,creationdate,loanamount,totaldue,termdays,referredby
0,8a858899538ddb8e015390510b321f08,301998974,4,NaT,NaT,10000,12250.0,30,NaN
1,8a858959537a097401537a4e316e25f7,301963615,10,NaT,NaT,40000,44000.0,30,NaN
2,8a8589c253ace09b0153af6ba58f1f31,301982236,6,2026-06-12 15:11:00,2026-06-12 15:04:00,20000,24500.0,30,NaN
3,8a858e095aae82b7015aae86ca1e030b,301971730,8,2026-06-12 00:54:00,2026-06-12 00:49:00,30000,34500.0,30,NaN
4,8a858e225a28c713015a30db5c48383d,301959177,4,2026-06-12 04:33:00,2026-06-12 04:27:00,20000,24500.0,30,NaN

In [11]:
# Check for missing values in train_perf_df
print('\nMissing values in train_perf_df:')
print(train_perf_df.isnull().sum())

# Check for missing values in test_perf_df
print('\nMissing values in test_perf_df:')
print(test_perf_df.isnull().sum())

Missing values in train_perf_df:
customerid          0
systemloanid        0
loannumber          0
approveddate        0
creationdate        0
loanamount          0
totaldue            0
termdays            0
referredby       3781
good_bad_flag       0
dtype: int64

Missing values in test_perf_df:
customerid         0
systemloanid       0
loannumber         0
approveddate     853
creationdate     859
loanamount         0
totaldue           0
termdays           0
referredby      1266
dtype: int64

## Data Cleaning and Preprocessing - Demographics Data

I will now examine the `train_demographics_df` and `test_demographics_df` for data types and missing values, and convert the 'birthdate' column to datetime objects.

In [12]:
print('--- train_demographics_df info ---')
train_demographics_df.info()
print('\n--- test_demographics_df info ---')
test_demographics_df.info()

--- train_demographics_df info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4346 entries, 0 to 4345
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   customerid                  4346 non-null   object
 1   birthdate                   4346 non-null   object
 2   bank_account_type           4346 non-null   object
 3   longitude_gps               4346 non-null   float64
 4   latitude_gps                4346 non-null   float64
 5   bank_name_clients           4346 non-null   object
 6   bank_branch_clients         51 non-null     object
 7   employment_status_clients   3698 non-null   object
 8   level_of_education_clients  587 non-null    object
dtypes: float64(2), object(7)
memory usage: 305.7+ KB

--- test_demographics_df info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1487 entries, 0 to 1486
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   customerid                  1487 non-null   object
 1   birthdate                   1487 non-null   object
 2   bank_account_type           1487 non-null   object
 3   longitude_gps               1487 non-null   float64
 4   latitude_gps                1487 non-null   float64
 5   bank_name_clients           1487 non-null   object
 6   bank_branch_clients         14 non-null     object
 7   employment_status_clients   1270 non-null   object
 8   level_of_education_clients  210 non-null    object
dtypes: float64(2), object(7)
memory usage: 104.7+ KB

In [13]:
# Convert 'birthdate' column to datetime objects for train_demographics_df
train_demographics_df['birthdate'] = pd.to_datetime(train_demographics_df['birthdate'], errors='coerce')

# Convert 'birthdate' column to datetime objects for test_demographics_df
test_demographics_df['birthdate'] = pd.to_datetime(test_demographics_df['birthdate'], errors='coerce')

print('\nBirthdate column converted for train_demographics_df:')
display(train_demographics_df.head())
print('\nBirthdate column converted for test_demographics_df:')
display(test_demographics_df.head())

Birthdate column converted for train_demographics_df:

,customerid,birthdate,bank_account_type,longitude_gps,latitude_gps,bank_name_clients,bank_branch_clients,employment_status_clients,level_of_education_clients
0,8a858e135cb22031015cbafc76964ebd,1973-10-10,Savings,3.319219,6.528604,GT Bank,NaN,NaN,NaN
1,8a858e275c7ea5ec015c82482d7c3996,1986-01-21,Savings,3.325598,7.119403,Sterling Bank,NaN,Permanent,NaN
2,8a858e5b5bd99460015bdc95cd485634,1987-04-01,Savings,5.746100,5.563174,Fidelity Bank,NaN,NaN,NaN
3,8a858efd5ca70688015cabd1f1e94b55,1991-07-19,Savings,3.362850,6.642485,GT Bank,NaN,Permanent,NaN
4,8a858e785acd3412015acd48f4920d04,1982-11-22,Savings,8.455332,11.971410,GT Bank,NaN,Permanent,NaN

Birthdate column converted for test_demographics_df:

,customerid,birthdate,bank_account_type,longitude_gps,latitude_gps,bank_name_clients,bank_branch_clients,employment_status_clients,level_of_education_clients
0,8a858f305c8dd672015c93b1db645db4,1976-08-28,Savings,5.296628,7.593965,Heritage Bank,NaN,Permanent,NaN
1,8a858f085a477386015a47fb049e49ca,1978-06-23,Savings,3.294513,6.596602,UBA,NaN,Permanent,NaN
2,8a858e6f5cd5e874015cd6f5634c39ad,1984-04-04,Savings,8.501912,7.729364,First Bank,NaN,Permanent,NaN
3,8a858e9d5bfd7037015bfdab79f61305,1983-05-28,Savings,3.318904,6.681595,UBA,NaN,Permanent,NaN
4,8a858fde56eb02280156eb6dafc128ac,1982-03-29,Savings,6.354624,4.949031,First Bank,NaN,Self-Employed,NaN

In [14]:
# Check for missing values in train_demographics_df
print('\nMissing values in train_demographics_df:')
print(train_demographics_df.isnull().sum())

# Check for missing values in test_demographics_df
print('\nMissing values in test_demographics_df:')
print(test_demographics_df.isnull().sum())

Missing values in train_demographics_df:
customerid                       0
birthdate                        0
bank_account_type                0
longitude_gps                    0
latitude_gps                     0
bank_name_clients                0
bank_branch_clients           4295
employment_status_clients      648
level_of_education_clients    3759
dtype: int64

Missing values in test_demographics_df:
customerid                       0
birthdate                        0
bank_account_type                0
longitude_gps                    0
latitude_gps                     0
bank_name_clients                0
bank_branch_clients           1473
employment_status_clients      217
level_of_education_clients    1277
dtype: int64

## Data Cleaning and Preprocessing - Previous Loans Data

I will now examine the `train_prev_loans_df` and `test_prev_loans_df` for data types and missing values, and convert relevant columns to datetime objects.

In [15]:
print('--- train_prev_loans_df info ---')
train_prev_loans_df.info()
print('\n--- test_prev_loans_df info ---')
test_prev_loans_df.info()

--- train_prev_loans_df info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18183 entries, 0 to 18182
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   customerid       18183 non-null  object
 1   systemloanid     18183 non-null  int64
 2   loannumber       18183 non-null  int64
 3   approveddate     18183 non-null  object
 4   creationdate     18183 non-null  object
 5   loanamount       18183 non-null  float64
 6   totaldue         18183 non-null  float64
 7   termdays         18183 non-null  int64
 8   closeddate       18183 non-null  object
 9   referredby       1026 non-null   object
 10  firstduedate     18183 non-null  object
 11  firstrepaiddate  18183 non-null  object
dtypes: float64(2), int64(3), object(7)
memory usage: 1.7+ MB

--- test_prev_loans_df info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5907 entries, 0 to 5906
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   customerid       5907 non-null   object
 1   systemloanid     5907 non-null   int64
 2   loannumber       5907 non-null   int64
 3   approveddate     5907 non-null   object
 4   creationdate     5907 non-null   object
 5   loanamount       5907 non-null   float64
 6   totaldue         5907 non-null   float64
 7   termdays         5907 non-null   int64
 8   closeddate       5907 non-null   object
 9   referredby       325 non-null    object
 10  firstduedate     5907 non-null   object
 11  firstrepaiddate  5907 non-null   object
dtypes: float64(2), int64(3), object(7)
memory usage: 553.9+ KB

In [16]:
# Convert date columns to datetime objects for train_prev_loans_df
for col in ['approveddate', 'creationdate', 'closeddate', 'firstduedate', 'firstrepaiddate']:
    train_prev_loans_df[col] = pd.to_datetime(train_prev_loans_df[col], errors='coerce')

# Convert date columns to datetime objects for test_prev_loans_df
for col in ['approveddate', 'creationdate', 'closeddate', 'firstduedate', 'firstrepaiddate']:
    test_prev_loans_df[col] = pd.to_datetime(test_prev_loans_df[col], errors='coerce')

print('\nDate columns converted for train_prev_loans_df:')
display(train_prev_loans_df.head())
print('\nDate columns converted for test_prev_loans_df:')
display(test_prev_loans_df.head())

Date columns converted for train_prev_loans_df:

,customerid,systemloanid,loannumber,approveddate,creationdate,loanamount,totaldue,termdays,closeddate,referredby,firstduedate,firstrepaiddate
0,8a2a81a74ce8c05d014cfb32a0da1049,301682320,2,2016-08-15 18:22:40,2016-08-15 17:22:32,10000.0,13000.0,30,2016-09-01 16:06:48,NaN,2016-09-14,2016-09-01 15:51:43
1,8a2a81a74ce8c05d014cfb32a0da1049,301883808,9,2017-04-28 18:39:07,2017-04-28 17:38:53,10000.0,13000.0,30,2017-05-28 14:44:49,NaN,2017-05-30,2017-05-26 00:00:00
2,8a2a81a74ce8c05d014cfb32a0da1049,301831714,8,2017-03-05 10:56:25,2017-03-05 09:56:19,20000.0,23800.0,30,2017-04-26 22:18:56,NaN,2017-04-04,2017-04-26 22:03:47
3,8a8588f35438fe12015444567666018e,301861541,5,2017-04-09 18:25:55,2017-04-09 17:25:42,10000.0,11500.0,15,2017-04-24 01:35:52,NaN,2017-04-24,2017-04-24 00:48:43
4,8a85890754145ace015429211b513e16,301941754,2,2017-06-17 09:29:57,2017-06-17 08:29:50,10000.0,11500.0,15,2017-07-14 21:18:43,NaN,2017-07-03,2017-07-14 21:08:35

Date columns converted for test_prev_loans_df:

,customerid,systemloanid,loannumber,approveddate,creationdate,loanamount,totaldue,termdays,closeddate,referredby,firstduedate,firstrepaiddate
0,8a858899538ddb8e015390510b321f08,301621635,3,2016-05-17 10:37:00,2016-05-17 09:36:55,10000.0,13000.0,30,2016-06-17 00:04:15,NaN,2016-06-16,2016-06-16 15:44:08
1,8a858959537a097401537a4e316e25f7,301810201,5,2017-02-04 21:28:59,2017-02-04 20:28:52,30000.0,36800.0,60,2017-03-02 16:22:58,NaN,2017-03-06,2017-03-02 16:07:47
2,8a858959537a097401537a4e316e25f7,301831255,6,2017-03-04 10:28:22,2017-03-04 09:28:16,30000.0,34400.0,30,2017-04-02 00:44:24,NaN,2017-04-03,2017-04-01 21:29:46
3,8a8589c253ace09b0153af6ba58f1f31,301627292,3,2016-06-02 14:27:14,2016-06-02 13:27:08,10000.0,13000.0,30,2016-07-04 11:34:04,NaN,2016-07-04,2016-07-04 11:19:01
4,8a8589c253ace09b0153af6ba58f1f31,301621095,2,2016-05-16 09:13:12,2016-05-16 08:13:04,10000.0,11500.0,15,2016-06-02 00:02:58,NaN,2016-05-31,2016-06-01 15:22:34

In [17]:
# Check for missing values in train_prev_loans_df
print('\nMissing values in train_prev_loans_df:')
print(train_prev_loans_df.isnull().sum())

# Check for missing values in test_prev_loans_df
print('\nMissing values in test_prev_loans_df:')
print(test_prev_loans_df.isnull().sum())

Missing values in train_prev_loans_df:
customerid             0
systemloanid           0
loannumber             0
approveddate           0
creationdate           0
loanamount             0
totaldue               0
termdays               0
closeddate             0
referredby         17157
firstduedate           0
firstrepaiddate        0
dtype: int64

Missing values in test_prev_loans_df:
customerid            0
systemloanid          0
loannumber            0
approveddate          0
creationdate          0
loanamount            0
totaldue              0
termdays              0
closeddate            0
referredby         5582
firstduedate          0
firstrepaiddate       0
dtype: int64

## Data Merging

I will now merge the performance and demographic dataframes using `customerid` as the key. This will create comprehensive training and testing datasets for further feature engineering and model building.

In [18]:
# Merge train_perf_df with train_demographics_df
train_df = pd.merge(train_perf_df, train_demographics_df, on='customerid', how='left')
print('Training data merged. First 5 rows:')
display(train_df.head())
print('\nTrain data info:')
train_df.info()

Training data merged. First 5 rows:

,customerid,systemloanid,loannumber,approveddate,creationdate,loanamount,totaldue,termdays,referredby,good_bad_flag,birthdate,bank_account_type,longitude_gps,latitude_gps,bank_name_clients,bank_branch_clients,employment_status_clients,level_of_education_clients
0,8a2a81a74ce8c05d014cfb32a0da1049,301994762,12,2017-07-25 08:22:56,2017-07-25 07:22:47,30000.0,34500.0,30,NaN,Good,1972-01-15,Other,3.432010,6.433055,Diamond Bank,NaN,Permanent,Post-Graduate
1,8a85886e54beabf90154c0a29ae757c0,301965204,2,2017-07-05 17:04:41,2017-07-05 16:04:18,15000.0,17250.0,30,NaN,Good,1985-08-23,Savings,3.885298,7.320700,GT Bank,"DUGBE,IBADAN",Permanent,Graduate
2,8a8588f35438fe12015444567666018e,301966580,7,2017-07-06 14:52:57,2017-07-06 13:52:51,20000.0,22250.0,15,NaN,Good,1984-09-18,Other,11.139350,10.292041,EcoBank,NaN,Permanent,NaN
3,8a85890754145ace015429211b513e16,301999343,3,2017-07-27 19:00:41,2017-07-27 18:00:35,10000.0,11500.0,15,NaN,Good,1977-10-10,Savings,3.985770,7.491708,First Bank,NaN,Permanent,NaN
4,8a858970548359cc0154883481981866,301962360,9,2017-07-03 23:42:45,2017-07-03 22:42:39,40000.0,44000.0,30,NaN,Good,1986-09-07,Other,7.457913,9.076574,GT Bank,NaN,Permanent,Primary

Train data info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4376 entries, 0 to 4375
Data columns (total 18 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   customerid                  4376 non-null   object
 1   systemloanid                4376 non-null   int64
 2   loannumber                  4376 non-null   int64
 3   approveddate                4376 non-null   datetime64[ns]
 4   creationdate                4376 non-null   datetime64[ns]
 5   loanamount                  4376 non-null   float64
 6   totaldue                    4376 non-null   float64
 7   termdays                    4376 non-null   int64
 8   referredby                  589 non-null    object
 9   good_bad_flag               4376 non-null   object
 10  birthdate                   3277 non-null   datetime64[ns]
 11  bank_account_type           3277 non-null   object
 12  longitude_gps               3277 non-null   float64
 13  latitude_gps                3277 non-null   float64
 14  bank_name_clients           3277 non-null   object
 15  bank_branch_clients         33 non-null     object
 16  employment_status_clients   2784 non-null   object
 17  level_of_education_clients  443 non-null    object
dtypes: datetime64[ns](3), float64(4), int64(3), object(8)
memory usage: 615.5+ KB

In [19]:
# Merge test_perf_df with test_demographics_df
test_df = pd.merge(test_perf_df, test_demographics_df, on='customerid', how='left')
print('\nTesting data merged. First 5 rows:')
display(test_df.head())
print('\nTest data info:')
test_df.info()

Testing data merged. First 5 rows:

,customerid,systemloanid,loannumber,approveddate,creationdate,loanamount,totaldue,termdays,referredby,birthdate,bank_account_type,longitude_gps,latitude_gps,bank_name_clients,bank_branch_clients,employment_status_clients,level_of_education_clients
0,8a858899538ddb8e015390510b321f08,301998974,4,NaT,NaT,10000,12250.0,30,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,8a858959537a097401537a4e316e25f7,301963615,10,NaT,NaT,40000,44000.0,30,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,8a8589c253ace09b0153af6ba58f1f31,301982236,6,2026-06-12 15:11:00,2026-06-12 15:04:00,20000,24500.0,30,NaN,1981-09-05,Savings,3.227945,6.586668,UBA,NaN,Permanent,NaN
3,8a858e095aae82b7015aae86ca1e030b,301971730,8,2026-06-12 00:54:00,2026-06-12 00:49:00,30000,34500.0,30,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,8a858e225a28c713015a30db5c48383d,301959177,4,2026-06-12 04:33:00,2026-06-12 04:27:00,20000,24500.0,30,NaN,1975-08-25,Savings,5.248368,13.059864,UBA,NaN,Permanent,NaN

Test data info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1450 entries, 0 to 1449
Data columns (total 17 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   customerid                  1450 non-null   object
 1   systemloanid                1450 non-null   int64
 2   loannumber                  1450 non-null   int64
 3   approveddate                597 non-null    datetime64[ns]
 4   creationdate                591 non-null    datetime64[ns]
 5   loanamount                  1450 non-null   int64
 6   totaldue                    1450 non-null   float64
 7   termdays                    1450 non-null   int64
 8   referredby                  184 non-null    object
 9   birthdate                   385 non-null    datetime64[ns]
 10  bank_account_type           385 non-null    object
 11  longitude_gps               385 non-null    float64
 12  latitude_gps                385 non-null    float64
 13  bank_name_clients           385 non-null    object
 14  bank_branch_clients         4 non-null      object
 15  employment_status_clients   332 non-null    object
 16  level_of_education_clients  47 non-null     object
dtypes: datetime64[ns](3), float64(3), int64(4), object(7)
memory usage: 192.7+ KB

## Feature Engineering from Previous Loans Data

I will aggregate the `train_prev_loans_df` and `test_prev_loans_df` to create features that summarize each customer's previous loan history. These aggregated features will then be merged into `train_df` and `test_df`.

In [20]:
# Aggregate features from train_prev_loans_df
train_prev_loans_agg = train_prev_loans_df.groupby('customerid').agg(
    num_prev_loans=('systemloanid', 'count'),
    avg_prev_loanamount=('loanamount', 'mean'),
    sum_prev_loanamount=('loanamount', 'sum'),
    avg_prev_totaldue=('totaldue', 'mean'),
    sum_prev_totaldue=('totaldue', 'sum'),
    avg_prev_termdays=('termdays', 'mean')
).reset_index()

# Merge aggregated previous loans features into train_df
train_df = pd.merge(train_df, train_prev_loans_agg, on='customerid', how='left')

print('Train data with previous loans aggregated features. First 5 rows:')
display(train_df.head())
print('\nTrain data info after merging previous loans features:')
train_df.info()

Train data with previous loans aggregated features. First 5 rows:

,customerid,systemloanid,loannumber,approveddate,creationdate,loanamount,totaldue,termdays,referredby,good_bad_flag,...,bank_name_clients,bank_branch_clients,employment_status_clients,level_of_education_clients,num_prev_loans,avg_prev_loanamount,sum_prev_loanamount,avg_prev_totaldue,sum_prev_totaldue,avg_prev_termdays
0,8a2a81a74ce8c05d014cfb32a0da1049,301994762,12,2017-07-25 08:22:56,2017-07-25 07:22:47,30000.0,34500.0,30,NaN,Good,...,Diamond Bank,NaN,Permanent,Post-Graduate,11.0,18181.818182,200000.0,22081.818182,242900.0,30.0
1,8a85886e54beabf90154c0a29ae757c0,301965204,2,2017-07-05 17:04:41,2017-07-05 16:04:18,15000.0,17250.0,30,NaN,Good,...,GT Bank,"DUGBE,IBADAN",Permanent,Graduate,NaN,NaN,NaN,NaN,NaN,NaN
2,8a8588f35438fe12015444567666018e,301966580,7,2017-07-06 14:52:57,2017-07-06 13:52:51,20000.0,22250.0,15,NaN,Good,...,EcoBank,NaN,Permanent,NaN,6.0,10000.000000,60000.0,11750.000000,70500.0,17.5
3,8a85890754145ace015429211b513e16,301999343,3,2017-07-27 19:00:41,2017-07-27 18:00:35,10000.0,11500.0,15,NaN,Good,...,First Bank,NaN,Permanent,NaN,2.0,10000.000000,20000.0,12250.000000,24500.0,22.5
4,8a858970548359cc0154883481981866,301962360,9,2017-07-03 23:42:45,2017-07-03 22:42:39,40000.0,44000.0,30,NaN,Good,...,GT Bank,NaN,Permanent,Primary,8.0,18750.000000,150000.0,23550.000000,188400.0,37.5

Train data info after merging previous loans features:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4376 entries, 0 to 4375
Data columns (total 24 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   customerid                  4376 non-null   object
 1   systemloanid                4376 non-null   int64
 2   loannumber                  4376 non-null   int64
 3   approveddate                4376 non-null   datetime64[ns]
 4   creationdate                4376 non-null   datetime64[ns]
 5   loanamount                  4376 non-null   float64
 6   totaldue                    4376 non-null   float64
 7   termdays                    4376 non-null   int64
 8   referredby                  589 non-null    object
 9   good_bad_flag               4376 non-null   object
 10  birthdate                   3277 non-null   datetime64[ns]
 11  bank_account_type           3277 non-null   object
 12  longitude_gps               3277 non-null   float64
 13  latitude_gps                3277 non-null   float64
 14  bank_name_clients           3277 non-null   object
 15  bank_branch_clients         33 non-null     object
 16  employment_status_clients   2784 non-null   object
 17  level_of_education_clients  443 non-null    object
 18  num_prev_loans              4367 non-null   float64
 19  avg_prev_loanamount         4367 non-null   float64
 20  sum_prev_loanamount         4367 non-null   float64
 21  avg_prev_totaldue           4367 non-null   float64
 22  sum_prev_totaldue           4367 non-null   float64
 23  avg_prev_termdays           4367 non-null   float64
dtypes: datetime64[ns](3), float64(10), int64(3), object(8)
memory usage: 820.6+ KB

In [21]:
# Aggregate features from test_prev_loans_df
test_prev_loans_agg = test_prev_loans_df.groupby('customerid').agg(
    num_prev_loans=('systemloanid', 'count'),
    avg_prev_loanamount=('loanamount', 'mean'),
    sum_prev_loanamount=('loanamount', 'sum'),
    avg_prev_totaldue=('totaldue', 'mean'),
    sum_prev_totaldue=('totaldue', 'sum'),
    avg_prev_termdays=('termdays', 'mean')
).reset_index()

# Merge aggregated previous loans features into test_df
test_df = pd.merge(test_df, test_prev_loans_agg, on='customerid', how='left')

print('\nTest data with previous loans aggregated features. First 5 rows:')
display(test_df.head())
print('\nTest data info after merging previous loans features:')
test_df.info()

Test data with previous loans aggregated features. First 5 rows:

,customerid,systemloanid,loannumber,approveddate,creationdate,loanamount,totaldue,termdays,referredby,birthdate,...,bank_name_clients,bank_branch_clients,employment_status_clients,level_of_education_clients,num_prev_loans,avg_prev_loanamount,sum_prev_loanamount,avg_prev_totaldue,sum_prev_totaldue,avg_prev_termdays
0,8a858899538ddb8e015390510b321f08,301998974,4,NaT,NaT,10000,12250.0,30,NaN,NaT,...,NaN,NaN,NaN,NaN,3.0,8666.666667,26000.0,10966.666667,32900.0,25.000000
1,8a858959537a097401537a4e316e25f7,301963615,10,NaT,NaT,40000,44000.0,30,NaN,NaT,...,NaN,NaN,NaN,NaN,9.0,23888.888889,215000.0,27600.000000,248400.0,31.666667
2,8a8589c253ace09b0153af6ba58f1f31,301982236,6,2026-06-12 15:11:00,2026-06-12 15:04:00,20000,24500.0,30,NaN,1981-09-05,...,UBA,NaN,Permanent,NaN,5.0,13000.000000,65000.0,15935.000000,79675.0,27.000000
3,8a858e095aae82b7015aae86ca1e030b,301971730,8,2026-06-12 00:54:00,2026-06-12 00:49:00,30000,34500.0,30,NaN,NaT,...,NaN,NaN,NaN,NaN,7.0,17142.857143,120000.0,19342.857143,135400.0,17.142857
4,8a858e225a28c713015a30db5c48383d,301959177,4,2026-06-12 04:33:00,2026-06-12 04:27:00,20000,24500.0,30,NaN,1975-08-25,...,UBA,NaN,Permanent,NaN,3.0,10000.000000,30000.0,12500.000000,37500.0,25.000000

Test data info after merging previous loans features:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1450 entries, 0 to 1449
Data columns (total 23 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   customerid                  1450 non-null   object
 1   systemloanid                1450 non-null   int64
 2   loannumber                  1450 non-null   int64
 3   approveddate                597 non-null    datetime64[ns]
 4   creationdate                591 non-null    datetime64[ns]
 5   loanamount                  1450 non-null   int64
 6   totaldue                    1450 non-null   float64
 7   termdays                    1450 non-null   int64
 8   referredby                  184 non-null    object
 9   birthdate                   385 non-null    datetime64[ns]
 10  bank_account_type           385 non-null    object
 11  longitude_gps               385 non-null    float64
 12  latitude_gps                385 non-null    float64
 13  bank_name_clients           385 non-null    object
 14  bank_branch_clients         4 non-null      object
 15  employment_status_clients   332 non-null    object
 16  level_of_education_clients  47 non-null     object
 17  num_prev_loans              1442 non-null   float64
 18  avg_prev_loanamount         1442 non-null   float64
 19  sum_prev_loanamount         1442 non-null   float64
 20  avg_prev_totaldue           1442 non-null   float64
 21  sum_prev_totaldue           1442 non-null   float64
 22  avg_prev_termdays           1442 non-null   float64
dtypes: datetime64[ns](3), float64(9), int64(4), object(7)
memory usage: 260.7+ KB

## Feature Engineering - Additional Features

I will create additional features from existing columns in both `train_df` and `test_df` to enhance the predictive power of our models. This includes extracting components from date columns, calculating durations, and creating categorical indicators.

In [22]:
# Feature Engineering for train_df

# Age from birthdate
current_date = pd.to_datetime('today')
train_df['age'] = (current_date - train_df['birthdate']).dt.days / 365.25

# Time since approveddate (days)
train_df['days_since_approved'] = (current_date - train_df['approveddate']).dt.days

# Loan duration (termdays)
train_df['loan_duration'] = train_df['termdays']

# Approved to creation days
train_df['approved_to_creation_days'] = (train_df['approveddate'] - train_df['creationdate']).dt.days

# Is referred
train_df['is_referred'] = train_df['referredby'].notna().astype(int)

# Extract date features
for col in ['approveddate', 'creationdate']:
    train_df[f'{col}_dayofweek'] = train_df[col].dt.dayofweek
    train_df[f'{col}_month'] = train_df[col].dt.month
    train_df[f'{col}_year'] = train_df[col].dt.year

print('Train data after additional feature engineering. First 5 rows:')
display(train_df.head())
print('\nTrain data info after additional feature engineering:')
train_df.info()

Train data after additional feature engineering. First 5 rows:

,customerid,systemloanid,loannumber,approveddate,creationdate,loanamount,totaldue,termdays,referredby,good_bad_flag,...,days_since_approved,loan_duration,approved_to_creation_days,is_referred,approveddate_dayofweek,approveddate_month,approveddate_year,creationdate_dayofweek,creationdate_month,creationdate_year
0,8a2a81a74ce8c05d014cfb32a0da1049,301994762,12,2017-07-25 08:22:56,2017-07-25 07:22:47,30000.0,34500.0,30,NaN,Good,...,3244,30,0,0,1,7,2017,1,7,2017
1,8a85886e54beabf90154c0a29ae757c0,301965204,2,2017-07-05 17:04:41,2017-07-05 16:04:18,15000.0,17250.0,30,NaN,Good,...,3263,30,0,0,2,7,2017,2,7,2017
2,8a8588f35438fe12015444567666018e,301966580,7,2017-07-06 14:52:57,2017-07-06 13:52:51,20000.0,22250.0,15,NaN,Good,...,3262,15,0,0,3,7,2017,3,7,2017
3,8a85890754145ace015429211b513e16,301999343,3,2017-07-27 19:00:41,2017-07-27 18:00:35,10000.0,11500.0,15,NaN,Good,...,3241,15,0,0,3,7,2017,3,7,2017
4,8a858970548359cc0154883481981866,301962360,9,2017-07-03 23:42:45,2017-07-03 22:42:39,40000.0,44000.0,30,NaN,Good,...,3265,30,0,0,0,7,2017,0,7,2017

Train data info after additional feature engineering:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4376 entries, 0 to 4375
Data columns (total 35 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   customerid                  4376 non-null   object
 1   systemloanid                4376 non-null   int64
 2   loannumber                  4376 non-null   int64
 3   approveddate                4376 non-null   datetime64[ns]
 4   creationdate                4376 non-null   datetime64[ns]
 5   loanamount                  4376 non-null   float64
 6   totaldue                    4376 non-null   float64
 7   termdays                    4376 non-null   int64
 8   referredby                  589 non-null    object
 9   good_bad_flag               4376 non-null   object
 10  birthdate                   3277 non-null   datetime64[ns]
 11  bank_account_type           3277 non-null   object
 12  longitude_gps               3277 non-null   float64
 13  latitude_gps                3277 non-null   float64
 14  bank_name_clients           3277 non-null   object
 15  bank_branch_clients         33 non-null     object
 16  employment_status_clients   2784 non-null   object
 17  level_of_education_clients  443 non-null    object
 18  num_prev_loans              4367 non-null   float64
 19  avg_prev_loanamount         4367 non-null   float64
 20  sum_prev_loanamount         4367 non-null   float64
 21  avg_prev_totaldue           4367 non-null   float64
 22  sum_prev_totaldue           4367 non-null   float64
 23  avg_prev_termdays           4367 non-null   float64
 24  age                         3277 non-null   float64
 25  days_since_approved         4376 non-null   int64
 26  loan_duration               4376 non-null   int64
 27  approved_to_creation_days   4376 non-null   int64
 28  is_referred                 4376 non-null   int64
 29  approveddate_dayofweek      4376 non-null   int32
 30  approveddate_month          4376 non-null   int32
 31  approveddate_year           4376 non-null   int32
 32  creationdate_dayofweek      4376 non-null   int32
 33  creationdate_month          4376 non-null   int32
 34  creationdate_year           4376 non-null   int32
dtypes: datetime64[ns](3), float64(11), int32(6), int64(7), object(8)
memory usage: 1.1+ MB

In [23]:
# Feature Engineering for test_df

# Age from birthdate
current_date = pd.to_datetime('today')
test_df['age'] = (current_date - test_df['birthdate']).dt.days / 365.25

# Time since approveddate (days)
test_df['days_since_approved'] = (current_date - test_df['approveddate']).dt.days

# Loan duration (termdays)
test_df['loan_duration'] = test_df['termdays']

# Approved to creation days
test_df['approved_to_creation_days'] = (test_df['approveddate'] - test_df['creationdate']).dt.days

# Is referred
test_df['is_referred'] = test_df['referredby'].notna().astype(int)

# Extract date features
for col in ['approveddate', 'creationdate']:
    test_df[f'{col}_dayofweek'] = test_df[col].dt.dayofweek
    test_df[f'{col}_month'] = test_df[col].dt.month
    test_df[f'{col}_year'] = test_df[col].dt.year

print('Test data after additional feature engineering. First 5 rows:')
display(test_df.head())
print('\nTest data info after additional feature engineering:')
test_df.info()

Test data after additional feature engineering. First 5 rows:

,customerid,systemloanid,loannumber,approveddate,creationdate,loanamount,totaldue,termdays,referredby,birthdate,...,days_since_approved,loan_duration,approved_to_creation_days,is_referred,approveddate_dayofweek,approveddate_month,approveddate_year,creationdate_dayofweek,creationdate_month,creationdate_year
0,8a858899538ddb8e015390510b321f08,301998974,4,NaT,NaT,10000,12250.0,30,NaN,NaT,...,NaN,30,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
1,8a858959537a097401537a4e316e25f7,301963615,10,NaT,NaT,40000,44000.0,30,NaN,NaT,...,NaN,30,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN
2,8a8589c253ace09b0153af6ba58f1f31,301982236,6,2026-06-12 15:11:00,2026-06-12 15:04:00,20000,24500.0,30,NaN,1981-09-05,...,-1.0,30,0.0,0,4.0,6.0,2026.0,4.0,6.0,2026.0
3,8a858e095aae82b7015aae86ca1e030b,301971730,8,2026-06-12 00:54:00,2026-06-12 00:49:00,30000,34500.0,30,NaN,NaT,...,0.0,30,0.0,0,4.0,6.0,2026.0,4.0,6.0,2026.0
4,8a858e225a28c713015a30db5c48383d,301959177,4,2026-06-12 04:33:00,2026-06-12 04:27:00,20000,24500.0,30,NaN,1975-08-25,...,0.0,30,0.0,0,4.0,6.0,2026.0,4.0,6.0,2026.0

Test data info after additional feature engineering:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1450 entries, 0 to 1449
Data columns (total 34 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   customerid                  1450 non-null   object
 1   systemloanid                1450 non-null   int64
 2   loannumber                  1450 non-null   int64
 3   approveddate                597 non-null    datetime64[ns]
 4   creationdate                591 non-null    datetime64[ns]
 5   loanamount                  1450 non-null   int64
 6   totaldue                    1450 non-null   float64
 7   termdays                    1450 non-null   int64
 8   referredby                  184 non-null    object
 9   birthdate                   385 non-null    datetime64[ns]
 10  bank_account_type           385 non-null    object
 11  longitude_gps               385 non-null    float64
 12  latitude_gps                385 non-null    float64
 13  bank_name_clients           385 non-null    object
 14  bank_branch_clients         4 non-null      object
 15  employment_status_clients   332 non-null    object
 16  level_of_education_clients  47 non-null     object
 17  num_prev_loans              1442 non-null   float64
 18  avg_prev_loanamount         1442 non-null   float64
 19  sum_prev_loanamount         1442 non-null   float64
 20  avg_prev_totaldue           1442 non-null   float64
 21  sum_prev_totaldue           1442 non-null   float64
 22  avg_prev_termdays           1442 non-null   float64
 23  age                         385 non-null    float64
 24  days_since_approved         597 non-null    float64
 25  loan_duration               1450 non-null   int64
 26  approved_to_creation_days   585 non-null    float64
 27  is_referred                 1450 non-null   int64
 28  approveddate_dayofweek      597 non-null    float64
 29  approveddate_month          597 non-null    float64
 30  approveddate_year           597 non-null    float64
 31  creationdate_dayofweek      591 non-null    float64
 32  creationdate_month          591 non-null    float64
 33  creationdate_year           591 non-null    float64
dtypes: datetime64[ns](3), float64(18), int64(6), object(7)
memory usage: 385.3+ KB

## Data Preparation for Modeling

I will now prepare the data for machine learning by handling categorical features and addressing missing values. Categorical columns will be converted using one-hot encoding.

In [24]:
# Convert 'good_bad_flag' to numerical (0/1) in train_df
train_df['good_bad_flag'] = train_df['good_bad_flag'].map({'Good': 1, 'Bad': 0})

print("Target variable 'good_bad_flag' converted to numerical:")
display(train_df[['customerid', 'good_bad_flag']].head())

Target variable 'good_bad_flag' converted to numerical:

                         customerid  good_bad_flag
0  8a2a81a74ce8c05d014cfb32a0da1049              1
1  8a85886e54beabf90154c0a29ae757c0              1
2  8a8588f35438fe12015444567666018e              1
3  8a85890754145ace015429211b513e16              1
4  8a858970548359cc0154883481981866              1

In [25]:
# Identify categorical columns for one-hot encoding
categorical_cols = [
    'bank_account_type',
    'bank_name_clients',
    'employment_status_clients',
    'level_of_education_clients'
]

# Apply one-hot encoding to training data
train_df = pd.get_dummies(train_df, columns=categorical_cols, dummy_na=False)

# Apply one-hot encoding to testing data
test_df = pd.get_dummies(test_df, columns=categorical_cols, dummy_na=False)

print('\nTrain data after one-hot encoding. First 5 rows:')
display(train_df.head())
print('\nTest data after one-hot encoding. First 5 rows:')
display(test_df.head())

Train data after one-hot encoding. First 5 rows:

,customerid,systemloanid,loannumber,approveddate,creationdate,loanamount,totaldue,termdays,referredby,good_bad_flag,...,employment_status_clients_Contract,employment_status_clients_Permanent,employment_status_clients_Retired,employment_status_clients_Self-Employed,employment_status_clients_Student,employment_status_clients_Unemployed,level_of_education_clients_Graduate,level_of_education_clients_Post-Graduate,level_of_education_clients_Primary,level_of_education_clients_Secondary
0,8a2a81a74ce8c05d014cfb32a0da1049,301994762,12,2017-07-25 08:22:56,2017-07-25 07:22:47,30000.0,34500.0,30,NaN,1,...,False,True,False,False,False,False,False,True,False,False
1,8a85886e54beabf90154c0a29ae757c0,301965204,2,2017-07-05 17:04:41,2017-07-05 16:04:18,15000.0,17250.0,30,NaN,1,...,False,True,False,False,False,False,True,False,False,False
2,8a8588f35438fe12015444567666018e,301966580,7,2017-07-06 14:52:57,2017-07-06 13:52:51,20000.0,22250.0,15,NaN,1,...,False,True,False,False,False,False,False,False,False,False
3,8a85890754145ace015429211b513e16,301999343,3,2017-07-27 19:00:41,2017-07-27 18:00:35,10000.0,11500.0,15,NaN,1,...,False,True,False,False,False,False,False,False,False,False
4,8a858970548359cc0154883481981866,301962360,9,2017-07-03 23:42:45,2017-07-03 22:42:39,40000.0,44000.0,30,NaN,1,...,False,True,False,False,False,False,False,False,True,False

Test data after one-hot encoding. First 5 rows:

,customerid,systemloanid,loannumber,approveddate,creationdate,loanamount,totaldue,termdays,referredby,birthdate,...,bank_name_clients_Zenith Bank,employment_status_clients_Permanent,employment_status_clients_Retired,employment_status_clients_Self-Employed,employment_status_clients_Student,employment_status_clients_Unemployed,level_of_education_clients_Graduate,level_of_education_clients_Post-Graduate,level_of_education_clients_Primary,level_of_education_clients_Secondary
0,8a858899538ddb8e015390510b321f08,301998974,4,NaT,NaT,10000,12250.0,30,NaN,NaT,...,False,False,False,False,False,False,False,False,False,False
1,8a858959537a097401537a4e316e25f7,301963615,10,NaT,NaT,40000,44000.0,30,NaN,NaT,...,False,False,False,False,False,False,False,False,False,False
2,8a8589c253ace09b0153af6ba58f1f31,301982236,6,2026-06-12 15:11:00,2026-06-12 15:04:00,20000,24500.0,30,NaN,1981-09-05,...,False,True,False,False,False,False,False,False,False,False
3,8a858e095aae82b7015aae86ca1e030b,301971730,8,2026-06-12 00:54:00,2026-06-12 00:49:00,30000,34500.0,30,NaN,NaT,...,False,False,False,False,False,False,False,False,False,False
4,8a858e225a28c713015a30db5c48383d,301959177,4,2026-06-12 04:33:00,2026-06-12 04:27:00,20000,24500.0,30,NaN,1975-08-25,...,False,True,False,False,False,False,False,False,False,False

In [26]:
# Align columns between train and test datasets after one-hot encoding
train_labels = train_df['good_bad_flag']
train_customer_ids = train_df['customerid']
test_customer_ids = test_df['customerid']

# Drop target and ID columns before alignment
train_df = train_df.drop(columns=['good_bad_flag', 'customerid'])
test_df = test_df.drop(columns=['customerid'])

common_cols = list(set(train_df.columns) & set(test_df.columns))

train_df = train_df[common_cols]
test_df = test_df[common_cols]

# Add missing columns to test_df (with zeros)
missing_in_test = set(train_df.columns) - set(test_df.columns)
for c in missing_in_test:
    test_df[c] = 0

# Add missing columns to train_df (with zeros)
missing_in_train = set(test_df.columns) - set(train_df.columns)
for c in missing_in_train:
    train_df[c] = 0

# Ensure the order of columns is the same
test_df = test_df[train_df.columns]

# Re-add target and ID columns
train_df['good_bad_flag'] = train_labels
train_df['customerid'] = train_customer_ids
test_df['customerid'] = test_customer_ids

print('\nTrain data after column alignment:')
print(train_df.shape)
print('\nTest data after column alignment:')
print(test_df.shape)

Train data after column alignment:
(4376, 59)

Test data after column alignment:
(1450, 58)

## Handle Missing Values and Feature Scaling

I will fill any remaining missing numerical values and then apply `StandardScaler` to normalize the numerical features in both the training and testing datasets.

In [31]:
# Drop original date, ID, referral, and bank branch columns as they have been used for feature engineering or are not needed directly for modeling
drop_cols = [
    'customerid', 'referredby',
    'approveddate', 'creationdate', 'birthdate',
    'bank_branch_clients' # Add bank_branch_clients to be dropped
]

train_df_processed = train_df.drop(columns=drop_cols, errors='ignore')
test_df_processed = test_df.drop(columns=drop_cols, errors='ignore')

# Separate target variable
X = train_df_processed.drop('good_bad_flag', axis=1)
y = train_df_processed['good_bad_flag']

# Identify numerical columns for imputation and scaling
numerical_cols = X.select_dtypes(include=['number', 'float']).columns

# Impute missing numerical values with the mean
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='mean')

X[numerical_cols] = imputer.fit_transform(X[numerical_cols])
test_df_processed[numerical_cols] = imputer.transform(test_df_processed[numerical_cols])

print('\nMissing values in X after imputation:')
print(X.isnull().sum().sum())
print('\nMissing values in test_df_processed after imputation:')
print(test_df_processed.isnull().sum().sum())

Missing values in X after imputation:
0

Missing values in test_df_processed after imputation:
0

In [32]:
from sklearn.preprocessing import StandardScaler

# Scale numerical features
scaler = StandardScaler()
X[numerical_cols] = scaler.fit_transform(X[numerical_cols])
test_df_processed[numerical_cols] = scaler.transform(test_df_processed[numerical_cols])

print('\nFeatures scaled. First 5 rows of X:')
display(X.head())
print('\nFirst 5 rows of test_df_processed:')
display(test_df_processed.head())

Features scaled. First 5 rows of X:

,bank_name_clients_Sterling Bank,bank_name_clients_Zenith Bank,bank_name_clients_Skye Bank,bank_name_clients_Diamond Bank,loan_duration,bank_account_type_Current,creationdate_dayofweek,bank_name_clients_GT Bank,avg_prev_termdays,approveddate_month,...,employment_status_clients_Unemployed,employment_status_clients_Retired,totaldue,employment_status_clients_Student,bank_name_clients_FCMB,bank_name_clients_UBA,level_of_education_clients_Post-Graduate,employment_status_clients_Self-Employed,avg_prev_loanamount,employment_status_clients_Permanent
0,False,False,False,True,0.063720,False,-0.902927,False,0.680269,0.0,...,False,False,1.109283,False,False,False,True,False,1.096467,True
1,False,False,False,False,0.063720,False,-0.374408,True,0.000000,0.0,...,False,False,-0.335157,False,False,False,False,False,0.000000,True
2,False,False,False,False,-1.239256,False,0.154111,False,-1.141882,0.0,...,False,False,0.083521,False,False,False,False,False,-0.604121,True
3,False,False,False,False,-1.239256,False,0.154111,False,-0.413022,0.0,...,False,False,-0.816638,False,False,False,False,False,-0.604121,True
4,False,False,False,False,0.063720,False,-1.431446,True,1.773559,0.0,...,False,False,1.904772,False,False,False,False,False,1.214564,True

First 5 rows of test_df_processed:

,bank_name_clients_Sterling Bank,bank_name_clients_Zenith Bank,bank_name_clients_Skye Bank,bank_name_clients_Diamond Bank,loan_duration,bank_account_type_Current,creationdate_dayofweek,bank_name_clients_GT Bank,avg_prev_termdays,approveddate_month,...,employment_status_clients_Unemployed,employment_status_clients_Retired,totaldue,employment_status_clients_Student,bank_name_clients_FCMB,bank_name_clients_UBA,level_of_education_clients_Post-Graduate,employment_status_clients_Self-Employed,avg_prev_loanamount,employment_status_clients_Permanent
0,False,False,False,False,0.06372,False,0.00000,False,-0.048592,0.0,...,False,False,-0.753836,False,False,False,False,False,-0.881254,False
1,False,False,False,False,0.06372,False,0.00000,False,0.923222,0.0,...,False,False,1.904772,False,False,False,False,False,2.282680,False
2,False,False,False,False,0.06372,False,0.68263,False,0.242953,-1.0,...,False,False,0.271926,False,False,True,False,False,0.019428,True
3,False,False,False,False,0.06372,False,0.68263,False,-1.193944,-1.0,...,False,False,1.109283,False,False,False,False,False,0.880520,False
4,False,False,False,False,0.06372,False,0.68263,False,-0.048592,-1.0,...,False,False,0.271926,False,False,True,False,False,-0.604121,True

## Model Selection, Training, and Evaluation

I will now split the processed training data into training and validation sets. Then, I'll train a `RandomForestClassifier` on the training set and evaluate its performance on the validation set using common classification metrics.

In [33]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score

# Split the training data into training and validation sets
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

print(f'X_train shape: {X_train.shape}')
print(f'X_val shape: {X_val.shape}')
print(f'y_train shape: {y_train.shape}')
print(f'y_val shape: {y_val.shape}')

X_train shape: (3500, 52)
X_val shape: (876, 52)
y_train shape: (3500,)
y_val shape: (876,)

In [34]:
# Train a RandomForestClassifier model
model = RandomForestClassifier(n_estimators=100, random_state=42, class_weight='balanced')
model.fit(X_train, y_train)

print('RandomForestClassifier model trained successfully.')

RandomForestClassifier model trained successfully.

In [35]:
# Make predictions on the validation set
y_pred = model.predict(X_val)
y_pred_proba = model.predict_proba(X_val)[:, 1]

# Evaluate the model
accuracy = accuracy_score(y_val, y_pred)
precision = precision_score(y_val, y_pred)
recall = recall_score(y_val, y_pred)
f1 = f1_score(y_val, y_pred)
roc_auc = roc_auc_score(y_val, y_pred_proba)

print(f'Accuracy: {accuracy:.4f}')
print(f'Precision: {precision:.4f}')
print(f'Recall: {recall:.4f}')
print(f'F1-Score: {f1:.4f}')
print(f'ROC AUC Score: {roc_auc:.4f}')

Accuracy: 0.7591
Precision: 0.7828
Recall: 0.9577
F1-Score: 0.8615
ROC AUC Score: 0.5919

## Generate Predictions and Submission File

I will now use the trained `RandomForestClassifier` model to predict the `good_bad_flag` for the `test_df_processed` dataset. Finally, I will format these predictions into a submission file, mapping customer IDs to their predicted `good_bad_flag`.

In [36]:
# Generate predictions on the test set
test_pred_proba = model.predict_proba(test_df_processed)[:, 1]

# Convert probabilities to binary predictions using a threshold (e.g., 0.5)
# If you want to optimize for a different metric, you might adjust this threshold
test_predictions = (test_pred_proba >= 0.5).astype(int)

print('Predictions generated for the test set.')

Predictions generated for the test set.

In [37]:
# Create the submission DataFrame
submission_df = pd.DataFrame({
    'customerid': test_customer_ids,
    'Good_Bad_flag': test_predictions
})

# Map numerical predictions back to 'Good' and 'Bad' if required by the submission format
# Assuming 'Good' is 1 and 'Bad' is 0
submission_df['Good_Bad_flag'] = submission_df['Good_Bad_flag'].map({1: 'Good', 0: 'Bad'})

# Display the first few rows of the submission file
print('Submission file preview:')
display(submission_df.head())

# Save the submission file to a CSV
submission_filename = 'submission.csv'
submission_df.to_csv(submission_filename, index=False)

print(f'Submission file saved as {submission_filename}')

Submission file preview:

                         customerid Good_Bad_flag
0  8a858899538ddb8e015390510b321f08          Good
1  8a858959537a097401537a4e316e25f7          Good
2  8a8589c253ace09b0153af6ba58f1f31          Good
3  8a858e095aae82b7015aae86ca1e030b          Good
4  8a858e225a28c713015a30db5c48383d          Good

Submission file saved as submission.csv